### ISSUE TITLE
鉴于taro-tailwind无法提交Issues，我只好来这里提问。

### ISSUE THREAD

**Issue by kkkk2323** [windedge/gatsby-tailwind-serif#4]
我在使用过程中发现taro-tailwind似乎无法使用@apply功能？这好像是因为小程序不支持@apply功能？还是有其他原因呢？

**Comment by kkkk2323** [comment]
配合Postcss就可以解决这个问题

**Comment by benny-eu** [comment]
你好,请问怎么配合 Postcss 使用?

**Comment by CraxGrix** [comment]
> 你好,请问怎么配合 Postcss 使用?
@apply这些功能写在tailwind.src.css这个样式文件里面，按照文档所说的把Postcss配置完成后执行下面这行命令，就会把相关的样式处理好然后生成为tailwind.css这个文件，然后在Taro中引入这个文件就可以了。
```
postcss ./src/tailwind.src.css -o ./src/tailwind.css
```

**Comment by kkkk2323** [comment]
> 你好,请问怎么配合 Postcss 使用?

@apply这些功能写在tailwind.src.css这个样式文件里面，按照文档所说的把Postcss配置完成后执行下面这行命令，就会把相关的样式处理好然后生成为tailwind.css这个文件，然后在Taro中引入这个文件就可以了。
```
postcss ./src/tailwind.src.css -o ./src/tailwind.css
```
